<script setup lang="ts">
const { weeks } = useWeeks()
</script>

<template>
  <div class="container mx-auto p-6 max-w-6xl">
    <UPageHero
      title="Welcome to WordyPond! 🐸"
      description="Learn new vocabulary words every week with fun games, exercises, and AI-generated sentences!"
      :links="[{
        label: 'Get Started',
        to: '/weeks',
        trailingIcon: 'i-lucide-arrow-right',
        size: 'xl'
      }]"
    />

    <UPageSection
      id="features"
      title="Learn Vocabulary the Fun Way!"
      description="WordyPond makes learning new words exciting with interactive games and activities designed for kids."
      :features="[{
        icon: 'i-lucide-book-open',
        title: 'Weekly Words',
        description: 'Parents can add 10 new vocabulary words each week for children to learn and practice.'
      }, {
        icon: 'i-lucide-gamepad-2',
        title: 'Interactive Games',
        description: 'Play spelling games with text-to-speech, memory matching, and fun quizzes to master new words.'
      }, {
        icon: 'i-lucide-sparkles',
        title: 'AI Sentences',
        description: 'Get creative example sentences using your vocabulary words, generated by AI to help with understanding.'
      }, {
        icon: 'i-lucide-trophy',
        title: 'Track Progress',
        description: 'See your scores and track how well you\'re learning each week\'s vocabulary words.'
      }, {
        icon: 'i-lucide-smile',
        title: 'Kid-Friendly',
        description: 'Colorful, playful design with emojis and fun animations to keep learning engaging and enjoyable.'
      }, {
        icon: 'i-lucide-save',
        title: 'Save Locally',
        description: 'All your weeks and words are saved in your browser, so you can continue where you left off anytime.'
      }]"
    />

    <UPageSection v-if="weeks.length > 0">
      <div class="text-center mb-8">
        <h2 class="text-3xl font-bold mb-4">
          Your Recent Weeks
        </h2>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
        <UCard
          v-for="week in weeks.slice(0, 3)"
          :key="week.id"
          class="hover:shadow-lg transition-shadow"
        >
          <template #header>
            <h3 class="text-xl font-bold">
              {{ week.title }}
            </h3>
          </template>

          <p class="text-sm text-muted mb-4">
            {{ week.words.length }} words
          </p>

          <template #footer>
            <div class="flex gap-2">
              <UButton
                :to="`/exercises/${week.id}`"
                icon="i-lucide-gamepad-2"
                size="sm"
                block
              >
                Play
              </UButton>
              <UButton
                :to="`/sentences/${week.id}`"
                icon="i-lucide-sparkles"
                size="sm"
                variant="outline"
                block
              >
                Sentences
              </UButton>
            </div>
          </template>
        </UCard>
      </div>

      <div class="text-center mt-8">
        <UButton to="/weeks" size="lg" variant="outline">
          View All Weeks
        </UButton>
      </div>
    </UPageSection>

    <UPageSection v-else>
      <UPageCTA
        title="Ready to Start Learning?"
        description="Create your first vocabulary week and begin your learning journey with fun games and activities!"
        variant="subtle"
        :links="[{
          label: 'Create First Week',
          to: '/weeks',
          trailingIcon: 'i-lucide-arrow-right',
          color: 'primary'
        }]"
      />
    </UPageSection>
  </div>
</template>
